"""DIMER inference package for the pinned ``google/pix2struct-textcaps-base`` checkpoint."""

from .pipeline import (
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MAX_PATCHES,
    MAX_PREFIX_CHARS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    Pix2StructTextCapsPipeline,
    caption_tokens,
    evaluation_report,
    keyword_hits,
    normalize_caption,
    stage_missing_files,
    text_recall,
    unigram_f1,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MAX_PATCHES",
    "MAX_PREFIX_CHARS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "Pix2StructTextCapsPipeline",
    "caption_tokens",
    "evaluation_report",
    "keyword_hits",
    "normalize_caption",
    "stage_missing_files",
    "text_recall",
    "unigram_f1",
    "validate_inputs",
    "verify_snapshot",
]
